apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zbt6580qv-go
  janus-idp.io/tekton: zbt6580qv-go
  backstage.io/kubernetes-id: zbt6580qv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zbt6580qv-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
