apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zbt6580qv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zbt6580qv-go 
  name: zbt6580qv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zbt6580qv-go 
